<?php 
    session_start();
    if(isset($_SESSION['facebook_access_token']))
    {
        header('Location:login-callback.php');
    }
    else
    {
        header('Location:index2.php');
    }
 ?>